
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/rmikhail/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-89-generic - x86_64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/build-env-jauj97c_/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-89-generic - x86_64
...
